### ISSUE TITLE
:sparkles: **The Improve Build Infra Project!** :sparkles:

### ISSUE THREAD

**Issue by snomos** [giellalt/giella-core#40]
Planned tasks
- [ ] Move all test targets from the `test/` dir to a `test/`subdir in the component being tested
- [ ] [Move all fst builds inside the `src/fst/` dir](https://github.com/giellalt/template-lang-und/issues/8)
- [ ] Remake the build rules for spellers
- [ ] [Fix speller filenames for CI](https://github.com/giellalt/giella-core/issues/3)
- [ ] [Add support for AltWS and other alternative orthographies](https://github.com/giellalt/giella-core/issues/2) etc to mobile spellers
- [ ] [Improve README's](https://github.com/giellalt/template-lang-und/issues/6)
- [ ] Document and define basic build compliance
- [ ] Add [maturity statistics](https://github.com/giellalt/template-lang-und/issues/6) to all language repos (in README)
- [ ] Prepare for less Autotools, more modernisation
- [ ] [Change jspwiki/forrest docs to Markdown](https://github.com/giellalt/giella-core/issues/7), for instant publishing on Github
